/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { AnalyticsData, HeatmapColorScheme, HeatmapData, HeatmapType, OperationTally, StatsMetric, StatsPanelLayout } from "./types/analytics";
import { RrwebEvent } from "./types/events";
import { DecompressErrorDetail, HeatmapReadyDetail, ReplayDblClickDetail, ReplayFullscreenChangeDetail, ReplayReadyDetail, ReplayTimeUpdateDetail, StatsReadyDetail } from "./types/component-props";
export { AnalyticsData, HeatmapColorScheme, HeatmapData, HeatmapType, OperationTally, StatsMetric, StatsPanelLayout } from "./types/analytics";
export { RrwebEvent } from "./types/events";
export { DecompressErrorDetail, HeatmapReadyDetail, ReplayDblClickDetail, ReplayFullscreenChangeDetail, ReplayReadyDetail, ReplayTimeUpdateDetail, StatsReadyDetail } from "./types/component-props";
export namespace Components {
    interface HeatmapCanvas {
        /**
          * @default 'warm'
         */
        "colorScheme": HeatmapColorScheme;
        "data": HeatmapData;
        /**
          * @default 0.6
         */
        "opacity": number;
    }
    /**
     * <replayer-controls> — Overlay-style playback controls for the web-replayer.
     * Features:
     *   - SVG icons for play/pause/replay with ripple effect
     *   - Custom progress slider with fill bar + hover tooltip
     *   - Speed pill buttons (one-click switching)
     *   - Frame step (forward/backward)
     *   - Skip-inactive toggle + fullscreen toggle
     *   - Keyboard-friendly, accessible (ARIA)
     */
    interface ReplayerControls {
        /**
          * @default false
         */
        "finished": boolean;
        /**
          * Whether the parent component is currently in fullscreen mode
          * @default false
         */
        "fullscreen": boolean;
        /**
          * @default false
         */
        "playing": boolean;
        /**
          * @default true
         */
        "skipInactive": boolean;
        /**
          * @default 1
         */
        "speed": number;
        /**
          * Total duration in ms — set once when data loads, passed as
          * @Prop (low-frequency change)
          * @default 0
         */
        "totalTime": number;
        "updateTimeDisplay": (currentTime: number, totalTime: number) => Promise<void>;
    }
    interface StatsChart {
        "breakdown": OperationTally[];
    }
    interface WebHeatmap {
        /**
          * @default 'warm'
         */
        "colorScheme": HeatmapColorScheme;
        "events": RrwebEvent[];
        /**
          * @default 0.6
         */
        "opacity": number;
        /**
          * @default 'all'
         */
        "type": HeatmapType;
    }
    interface WebReplayer {
        /**
          * Auto-hide controls when mouse idle for a while. Default false.
          * @default false
         */
        "autoHideControls": boolean;
        /**
          * @default false
         */
        "autoPlay": boolean;
        /**
          * Session data — accepts multiple formats: - Compressed string (LZ-String URI-safe/UTF-16/Base64, pako gzip base64) - JSON-serialized string (JSON.stringify of an event array) - Raw event array (RrwebEvent[] or any[] with timestamp+type fields) - Chunked shard array: each element has a `fcontent` string (LZ-String   base64 compressed event fragment), `fevent_order`, `fevent_count`.   Chunks are ordered by `fevent_order`, decompressed, merged into one   event array (see mergeChunkedEvents). Auto-detection picks the optimal path: chunk arrays decompress+merge, raw arrays skip decompress+parse, JSON strings skip decompress, compressed strings go through full pipeline.
         */
        "data": string | any[];
        /**
          * Maximum scale ratio in fullscreen mode (default 1.15). Prevents small recorded pages from being blown up too large. When the contain-mode scale exceeds this ratio, the replay is capped at original size × fullscreenMaxRatio and centered in the container. Only applies in fullscreen — non-fullscreen scaling is unchanged.
          * @default 1.15
         */
        "fullscreenMaxRatio": number;
        "getAnalytics": () => Promise<AnalyticsData | null>;
        "getEvents": () => Promise<RrwebEvent[]>;
        /**
          * Whether the <web-replayer> host is currently in fullscreen mode.
         */
        "getIsFullscreen": () => Promise<boolean>;
        /**
          * Component height — accepts CSS values: "888px", "60vh", or bare number "888" (treated as px).
         */
        "height"?: string;
        /**
          * Enable user interaction with the replayed UI (clicks, inputs, scrolling). Default false — replay is non-interactive for stability. When true, calls replayer.enableInteract() which sets pointer-events: auto on the replay iframe. Note: enabling interaction may cause instability (e.g., navigating away via external links). Use with caution.
          * @default false
         */
        "interact": boolean;
        "pause": () => Promise<void>;
        "play": () => Promise<void>;
        "seek": (time: number) => Promise<void>;
        /**
          * @default true
         */
        "showControls": boolean;
        /**
          * Show heatmap overlay. Default false.
          * @default false
         */
        "showHeatmap": boolean;
        /**
          * Show stats panel. Default false.
          * @default false
         */
        "showStats": boolean;
        /**
          * @default 1
         */
        "speed": number;
        /**
          * @default 0
         */
        "startTime": number;
        /**
          * Allow scripts execution in the replay iframe. Default false for security. When true, rrweb creates iframe with sandbox="allow-same-origin allow-scripts". When false, rrweb uses sandboxed iframe with only "allow-same-origin" (scripts blocked). The "Blocked script execution" console warning when unsafeAllowScripts=false is expected — rrweb rebuilds the DOM via mutations, not by executing recorded scripts.
          * @default true
         */
        "unsafeAllowScripts": boolean;
        /**
          * Component width — accepts CSS values: "85%", "800px", "50vw", or bare number "800" (treated as px).
         */
        "width"?: string;
    }
    interface WebStatsPanel {
        "events": RrwebEvent[];
        /**
          * @default 'sidebar'
         */
        "layout": StatsPanelLayout;
        /**
          * @default ['clicks', 'scrolls', 'inputs', 'duration', 'path']
         */
        "metrics": StatsMetric[];
    }
    interface WrTooltip {
        /**
          * @default 'top'
         */
        "position": 'top' | 'bottom' | 'left' | 'right';
        "text": string;
    }
}
export interface ReplayerControlsCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLReplayerControlsElement;
}
export interface WebReplayerCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLWebReplayerElement;
}
declare global {
    interface HTMLHeatmapCanvasElement extends Components.HeatmapCanvas, HTMLStencilElement {
    }
    var HTMLHeatmapCanvasElement: {
        prototype: HTMLHeatmapCanvasElement;
        new (): HTMLHeatmapCanvasElement;
    };
    interface HTMLReplayerControlsElementEventMap {
        "playPause": void;
        "seek": number;
        "speedChange": number;
        "stepForward": void;
        "stepBackward": void;
        "fullscreenToggle": void;
        "skipInactiveToggle": boolean;
    }
    /**
     * <replayer-controls> — Overlay-style playback controls for the web-replayer.
     * Features:
     *   - SVG icons for play/pause/replay with ripple effect
     *   - Custom progress slider with fill bar + hover tooltip
     *   - Speed pill buttons (one-click switching)
     *   - Frame step (forward/backward)
     *   - Skip-inactive toggle + fullscreen toggle
     *   - Keyboard-friendly, accessible (ARIA)
     */
    interface HTMLReplayerControlsElement extends Components.ReplayerControls, HTMLStencilElement {
        addEventListener<K extends keyof HTMLReplayerControlsElementEventMap>(type: K, listener: (this: HTMLReplayerControlsElement, ev: ReplayerControlsCustomEvent<HTMLReplayerControlsElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLReplayerControlsElementEventMap>(type: K, listener: (this: HTMLReplayerControlsElement, ev: ReplayerControlsCustomEvent<HTMLReplayerControlsElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLReplayerControlsElement: {
        prototype: HTMLReplayerControlsElement;
        new (): HTMLReplayerControlsElement;
    };
    interface HTMLStatsChartElement extends Components.StatsChart, HTMLStencilElement {
    }
    var HTMLStatsChartElement: {
        prototype: HTMLStatsChartElement;
        new (): HTMLStatsChartElement;
    };
    interface HTMLWebHeatmapElement extends Components.WebHeatmap, HTMLStencilElement {
    }
    var HTMLWebHeatmapElement: {
        prototype: HTMLWebHeatmapElement;
        new (): HTMLWebHeatmapElement;
    };
    interface HTMLWebReplayerElementEventMap {
        "replayReady": ReplayReadyDetail;
        "replayStart": void;
        "replayPause": void;
        "replayFinish": void;
        "replayTimeUpdate": ReplayTimeUpdateDetail;
        "heatmapReady": HeatmapReadyDetail;
        "statsReady": StatsReadyDetail;
        "decompressError": DecompressErrorDetail;
        "replayFullscreenChange": ReplayFullscreenChangeDetail;
        "replayDblClick": ReplayDblClickDetail;
    }
    interface HTMLWebReplayerElement extends Components.WebReplayer, HTMLStencilElement {
        addEventListener<K extends keyof HTMLWebReplayerElementEventMap>(type: K, listener: (this: HTMLWebReplayerElement, ev: WebReplayerCustomEvent<HTMLWebReplayerElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLWebReplayerElementEventMap>(type: K, listener: (this: HTMLWebReplayerElement, ev: WebReplayerCustomEvent<HTMLWebReplayerElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLWebReplayerElement: {
        prototype: HTMLWebReplayerElement;
        new (): HTMLWebReplayerElement;
    };
    interface HTMLWebStatsPanelElement extends Components.WebStatsPanel, HTMLStencilElement {
    }
    var HTMLWebStatsPanelElement: {
        prototype: HTMLWebStatsPanelElement;
        new (): HTMLWebStatsPanelElement;
    };
    interface HTMLWrTooltipElement extends Components.WrTooltip, HTMLStencilElement {
    }
    var HTMLWrTooltipElement: {
        prototype: HTMLWrTooltipElement;
        new (): HTMLWrTooltipElement;
    };
    interface HTMLElementTagNameMap {
        "heatmap-canvas": HTMLHeatmapCanvasElement;
        "replayer-controls": HTMLReplayerControlsElement;
        "stats-chart": HTMLStatsChartElement;
        "web-heatmap": HTMLWebHeatmapElement;
        "web-replayer": HTMLWebReplayerElement;
        "web-stats-panel": HTMLWebStatsPanelElement;
        "wr-tooltip": HTMLWrTooltipElement;
    }
}
declare namespace LocalJSX {
    type OneOf<K extends string, PropT, AttrT = PropT> = { [P in K]: PropT } & { [P in `attr:${K}` | `prop:${K}`]?: never } | { [P in `attr:${K}`]: AttrT } & { [P in K | `prop:${K}`]?: never } | { [P in `prop:${K}`]: PropT } & { [P in K | `attr:${K}`]?: never };

    interface HeatmapCanvas {
        /**
          * @default 'warm'
         */
        "colorScheme"?: HeatmapColorScheme;
        "data": HeatmapData;
        /**
          * @default 0.6
         */
        "opacity"?: number;
    }
    /**
     * <replayer-controls> — Overlay-style playback controls for the web-replayer.
     * Features:
     *   - SVG icons for play/pause/replay with ripple effect
     *   - Custom progress slider with fill bar + hover tooltip
     *   - Speed pill buttons (one-click switching)
     *   - Frame step (forward/backward)
     *   - Skip-inactive toggle + fullscreen toggle
     *   - Keyboard-friendly, accessible (ARIA)
     */
    interface ReplayerControls {
        /**
          * @default false
         */
        "finished"?: boolean;
        /**
          * Whether the parent component is currently in fullscreen mode
          * @default false
         */
        "fullscreen"?: boolean;
        "onFullscreenToggle"?: (event: ReplayerControlsCustomEvent<void>) => void;
        "onPlayPause"?: (event: ReplayerControlsCustomEvent<void>) => void;
        "onSeek"?: (event: ReplayerControlsCustomEvent<number>) => void;
        "onSkipInactiveToggle"?: (event: ReplayerControlsCustomEvent<boolean>) => void;
        "onSpeedChange"?: (event: ReplayerControlsCustomEvent<number>) => void;
        "onStepBackward"?: (event: ReplayerControlsCustomEvent<void>) => void;
        "onStepForward"?: (event: ReplayerControlsCustomEvent<void>) => void;
        /**
          * @default false
         */
        "playing"?: boolean;
        /**
          * @default true
         */
        "skipInactive"?: boolean;
        /**
          * @default 1
         */
        "speed"?: number;
        /**
          * Total duration in ms — set once when data loads, passed as
          * @Prop (low-frequency change)
          * @default 0
         */
        "totalTime"?: number;
    }
    interface StatsChart {
        "breakdown": OperationTally[];
    }
    interface WebHeatmap {
        /**
          * @default 'warm'
         */
        "colorScheme"?: HeatmapColorScheme;
        "events": RrwebEvent[];
        /**
          * @default 0.6
         */
        "opacity"?: number;
        /**
          * @default 'all'
         */
        "type"?: HeatmapType;
    }
    interface WebReplayer {
        /**
          * Auto-hide controls when mouse idle for a while. Default false.
          * @default false
         */
        "autoHideControls"?: boolean;
        /**
          * @default false
         */
        "autoPlay"?: boolean;
        /**
          * Session data — accepts multiple formats: - Compressed string (LZ-String URI-safe/UTF-16/Base64, pako gzip base64) - JSON-serialized string (JSON.stringify of an event array) - Raw event array (RrwebEvent[] or any[] with timestamp+type fields) - Chunked shard array: each element has a `fcontent` string (LZ-String   base64 compressed event fragment), `fevent_order`, `fevent_count`.   Chunks are ordered by `fevent_order`, decompressed, merged into one   event array (see mergeChunkedEvents). Auto-detection picks the optimal path: chunk arrays decompress+merge, raw arrays skip decompress+parse, JSON strings skip decompress, compressed strings go through full pipeline.
         */
        "data": string | any[];
        /**
          * Maximum scale ratio in fullscreen mode (default 1.15). Prevents small recorded pages from being blown up too large. When the contain-mode scale exceeds this ratio, the replay is capped at original size × fullscreenMaxRatio and centered in the container. Only applies in fullscreen — non-fullscreen scaling is unchanged.
          * @default 1.15
         */
        "fullscreenMaxRatio"?: number;
        /**
          * Component height — accepts CSS values: "888px", "60vh", or bare number "888" (treated as px).
         */
        "height"?: string;
        /**
          * Enable user interaction with the replayed UI (clicks, inputs, scrolling). Default false — replay is non-interactive for stability. When true, calls replayer.enableInteract() which sets pointer-events: auto on the replay iframe. Note: enabling interaction may cause instability (e.g., navigating away via external links). Use with caution.
          * @default false
         */
        "interact"?: boolean;
        "onDecompressError"?: (event: WebReplayerCustomEvent<DecompressErrorDetail>) => void;
        "onHeatmapReady"?: (event: WebReplayerCustomEvent<HeatmapReadyDetail>) => void;
        /**
          * Emitted when the replay viewport is double-clicked. Carries the current fullscreen state so listeners can react (e.g., toggle fullscreen) without a separate query.
         */
        "onReplayDblClick"?: (event: WebReplayerCustomEvent<ReplayDblClickDetail>) => void;
        "onReplayFinish"?: (event: WebReplayerCustomEvent<void>) => void;
        "onReplayFullscreenChange"?: (event: WebReplayerCustomEvent<ReplayFullscreenChangeDetail>) => void;
        "onReplayPause"?: (event: WebReplayerCustomEvent<void>) => void;
        "onReplayReady"?: (event: WebReplayerCustomEvent<ReplayReadyDetail>) => void;
        "onReplayStart"?: (event: WebReplayerCustomEvent<void>) => void;
        "onReplayTimeUpdate"?: (event: WebReplayerCustomEvent<ReplayTimeUpdateDetail>) => void;
        "onStatsReady"?: (event: WebReplayerCustomEvent<StatsReadyDetail>) => void;
        /**
          * @default true
         */
        "showControls"?: boolean;
        /**
          * Show heatmap overlay. Default false.
          * @default false
         */
        "showHeatmap"?: boolean;
        /**
          * Show stats panel. Default false.
          * @default false
         */
        "showStats"?: boolean;
        /**
          * @default 1
         */
        "speed"?: number;
        /**
          * @default 0
         */
        "startTime"?: number;
        /**
          * Allow scripts execution in the replay iframe. Default false for security. When true, rrweb creates iframe with sandbox="allow-same-origin allow-scripts". When false, rrweb uses sandboxed iframe with only "allow-same-origin" (scripts blocked). The "Blocked script execution" console warning when unsafeAllowScripts=false is expected — rrweb rebuilds the DOM via mutations, not by executing recorded scripts.
          * @default true
         */
        "unsafeAllowScripts"?: boolean;
        /**
          * Component width — accepts CSS values: "85%", "800px", "50vw", or bare number "800" (treated as px).
         */
        "width"?: string;
    }
    interface WebStatsPanel {
        "events": RrwebEvent[];
        /**
          * @default 'sidebar'
         */
        "layout"?: StatsPanelLayout;
        /**
          * @default ['clicks', 'scrolls', 'inputs', 'duration', 'path']
         */
        "metrics"?: StatsMetric[];
    }
    interface WrTooltip {
        /**
          * @default 'top'
         */
        "position"?: 'top' | 'bottom' | 'left' | 'right';
        "text": string;
    }

    interface HeatmapCanvasAttributes {
        "opacity": number;
        "colorScheme": HeatmapColorScheme;
    }
    interface ReplayerControlsAttributes {
        "playing": boolean;
        "speed": number;
        "skipInactive": boolean;
        "finished": boolean;
        "fullscreen": boolean;
        "totalTime": number;
    }
    interface WebHeatmapAttributes {
        "type": HeatmapType;
        "opacity": number;
        "colorScheme": HeatmapColorScheme;
    }
    interface WebReplayerAttributes {
        "data": string | any[];
        "width": string;
        "height": string;
        "autoPlay": boolean;
        "speed": number;
        "showControls": boolean;
        "showHeatmap": boolean;
        "showStats": boolean;
        "autoHideControls": boolean;
        "fullscreenMaxRatio": number;
        "startTime": number;
        "unsafeAllowScripts": boolean;
        "interact": boolean;
    }
    interface WebStatsPanelAttributes {
        "layout": StatsPanelLayout;
    }
    interface WrTooltipAttributes {
        "text": string;
        "position": 'top' | 'bottom' | 'left' | 'right';
    }

    interface IntrinsicElements {
        "heatmap-canvas": Omit<HeatmapCanvas, keyof HeatmapCanvasAttributes> & { [K in keyof HeatmapCanvas & keyof HeatmapCanvasAttributes]?: HeatmapCanvas[K] } & { [K in keyof HeatmapCanvas & keyof HeatmapCanvasAttributes as `attr:${K}`]?: HeatmapCanvasAttributes[K] } & { [K in keyof HeatmapCanvas & keyof HeatmapCanvasAttributes as `prop:${K}`]?: HeatmapCanvas[K] };
        "replayer-controls": Omit<ReplayerControls, keyof ReplayerControlsAttributes> & { [K in keyof ReplayerControls & keyof ReplayerControlsAttributes]?: ReplayerControls[K] } & { [K in keyof ReplayerControls & keyof ReplayerControlsAttributes as `attr:${K}`]?: ReplayerControlsAttributes[K] } & { [K in keyof ReplayerControls & keyof ReplayerControlsAttributes as `prop:${K}`]?: ReplayerControls[K] };
        "stats-chart": StatsChart;
        "web-heatmap": Omit<WebHeatmap, keyof WebHeatmapAttributes> & { [K in keyof WebHeatmap & keyof WebHeatmapAttributes]?: WebHeatmap[K] } & { [K in keyof WebHeatmap & keyof WebHeatmapAttributes as `attr:${K}`]?: WebHeatmapAttributes[K] } & { [K in keyof WebHeatmap & keyof WebHeatmapAttributes as `prop:${K}`]?: WebHeatmap[K] };
        "web-replayer": Omit<WebReplayer, keyof WebReplayerAttributes> & { [K in keyof WebReplayer & keyof WebReplayerAttributes]?: WebReplayer[K] } & { [K in keyof WebReplayer & keyof WebReplayerAttributes as `attr:${K}`]?: WebReplayerAttributes[K] } & { [K in keyof WebReplayer & keyof WebReplayerAttributes as `prop:${K}`]?: WebReplayer[K] } & OneOf<"data", WebReplayer["data"], WebReplayerAttributes["data"]>;
        "web-stats-panel": Omit<WebStatsPanel, keyof WebStatsPanelAttributes> & { [K in keyof WebStatsPanel & keyof WebStatsPanelAttributes]?: WebStatsPanel[K] } & { [K in keyof WebStatsPanel & keyof WebStatsPanelAttributes as `attr:${K}`]?: WebStatsPanelAttributes[K] } & { [K in keyof WebStatsPanel & keyof WebStatsPanelAttributes as `prop:${K}`]?: WebStatsPanel[K] };
        "wr-tooltip": Omit<WrTooltip, keyof WrTooltipAttributes> & { [K in keyof WrTooltip & keyof WrTooltipAttributes]?: WrTooltip[K] } & { [K in keyof WrTooltip & keyof WrTooltipAttributes as `attr:${K}`]?: WrTooltipAttributes[K] } & { [K in keyof WrTooltip & keyof WrTooltipAttributes as `prop:${K}`]?: WrTooltip[K] } & OneOf<"text", WrTooltip["text"], WrTooltipAttributes["text"]>;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "heatmap-canvas": LocalJSX.IntrinsicElements["heatmap-canvas"] & JSXBase.HTMLAttributes<HTMLHeatmapCanvasElement>;
            /**
             * <replayer-controls> — Overlay-style playback controls for the web-replayer.
             * Features:
             *   - SVG icons for play/pause/replay with ripple effect
             *   - Custom progress slider with fill bar + hover tooltip
             *   - Speed pill buttons (one-click switching)
             *   - Frame step (forward/backward)
             *   - Skip-inactive toggle + fullscreen toggle
             *   - Keyboard-friendly, accessible (ARIA)
             */
            "replayer-controls": LocalJSX.IntrinsicElements["replayer-controls"] & JSXBase.HTMLAttributes<HTMLReplayerControlsElement>;
            "stats-chart": LocalJSX.IntrinsicElements["stats-chart"] & JSXBase.HTMLAttributes<HTMLStatsChartElement>;
            "web-heatmap": LocalJSX.IntrinsicElements["web-heatmap"] & JSXBase.HTMLAttributes<HTMLWebHeatmapElement>;
            "web-replayer": LocalJSX.IntrinsicElements["web-replayer"] & JSXBase.HTMLAttributes<HTMLWebReplayerElement>;
            "web-stats-panel": LocalJSX.IntrinsicElements["web-stats-panel"] & JSXBase.HTMLAttributes<HTMLWebStatsPanelElement>;
            "wr-tooltip": LocalJSX.IntrinsicElements["wr-tooltip"] & JSXBase.HTMLAttributes<HTMLWrTooltipElement>;
        }
    }
}
