/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { AnalyticsData, HeatmapColorScheme, HeatmapData, HeatmapType, OperationTally, StatsMetric, StatsPanelLayout } from "./types/analytics";
import { RrwebEvent } from "./types/events";
import { DecompressErrorDetail, HeatmapReadyDetail, ReplayReadyDetail, ReplayTimeUpdateDetail, StatsReadyDetail } from "./types/component-props";
export { AnalyticsData, HeatmapColorScheme, HeatmapData, HeatmapType, OperationTally, StatsMetric, StatsPanelLayout } from "./types/analytics";
export { RrwebEvent } from "./types/events";
export { DecompressErrorDetail, HeatmapReadyDetail, ReplayReadyDetail, ReplayTimeUpdateDetail, StatsReadyDetail } from "./types/component-props";
export namespace Components {
    interface HeatmapCanvas {
        /**
          * @default 'warm'
         */
        "colorScheme": HeatmapColorScheme;
        "data": HeatmapData;
        /**
          * @default 0.6
         */
        "opacity": number;
    }
    interface ReplayerControls {
        /**
          * @default 0
         */
        "currentTime": number;
        /**
          * @default false
         */
        "playing": boolean;
        /**
          * @default 1
         */
        "speed": number;
        /**
          * @default 0
         */
        "totalTime": number;
    }
    interface StatsChart {
        "breakdown": OperationTally[];
    }
    interface WebHeatmap {
        /**
          * @default 'warm'
         */
        "colorScheme": HeatmapColorScheme;
        "events": RrwebEvent[];
        /**
          * @default 0.6
         */
        "opacity": number;
        /**
          * @default 'all'
         */
        "type": HeatmapType;
    }
    interface WebReplayer {
        /**
          * @default false
         */
        "autoPlay": boolean;
        "data": string;
        "getAnalytics": () => Promise<AnalyticsData | null>;
        "getEvents": () => Promise<RrwebEvent[]>;
        "height"?: number;
        "pause": () => Promise<void>;
        "play": () => Promise<void>;
        "seek": (time: number) => Promise<void>;
        /**
          * @default true
         */
        "showControls": boolean;
        /**
          * @default false
         */
        "showHeatmap": boolean;
        /**
          * @default false
         */
        "showStats": boolean;
        /**
          * @default 1
         */
        "speed": number;
        /**
          * @default 0
         */
        "startTime": number;
        "width"?: number;
    }
    interface WebStatsPanel {
        "events": RrwebEvent[];
        /**
          * @default 'sidebar'
         */
        "layout": StatsPanelLayout;
        /**
          * @default ['clicks', 'scrolls', 'inputs', 'duration', 'path']
         */
        "metrics": StatsMetric[];
    }
    interface WrTooltip {
        /**
          * @default 'top'
         */
        "position": 'top' | 'bottom' | 'left' | 'right';
        "text": string;
    }
}
export interface ReplayerControlsCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLReplayerControlsElement;
}
export interface WebReplayerCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLWebReplayerElement;
}
declare global {
    interface HTMLHeatmapCanvasElement extends Components.HeatmapCanvas, HTMLStencilElement {
    }
    var HTMLHeatmapCanvasElement: {
        prototype: HTMLHeatmapCanvasElement;
        new (): HTMLHeatmapCanvasElement;
    };
    interface HTMLReplayerControlsElementEventMap {
        "playPause": void;
        "seek": number;
        "speedChange": number;
    }
    interface HTMLReplayerControlsElement extends Components.ReplayerControls, HTMLStencilElement {
        addEventListener<K extends keyof HTMLReplayerControlsElementEventMap>(type: K, listener: (this: HTMLReplayerControlsElement, ev: ReplayerControlsCustomEvent<HTMLReplayerControlsElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLReplayerControlsElementEventMap>(type: K, listener: (this: HTMLReplayerControlsElement, ev: ReplayerControlsCustomEvent<HTMLReplayerControlsElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLReplayerControlsElement: {
        prototype: HTMLReplayerControlsElement;
        new (): HTMLReplayerControlsElement;
    };
    interface HTMLStatsChartElement extends Components.StatsChart, HTMLStencilElement {
    }
    var HTMLStatsChartElement: {
        prototype: HTMLStatsChartElement;
        new (): HTMLStatsChartElement;
    };
    interface HTMLWebHeatmapElement extends Components.WebHeatmap, HTMLStencilElement {
    }
    var HTMLWebHeatmapElement: {
        prototype: HTMLWebHeatmapElement;
        new (): HTMLWebHeatmapElement;
    };
    interface HTMLWebReplayerElementEventMap {
        "replayReady": ReplayReadyDetail;
        "replayStart": void;
        "replayPause": void;
        "replayFinish": void;
        "replayTimeUpdate": ReplayTimeUpdateDetail;
        "heatmapReady": HeatmapReadyDetail;
        "statsReady": StatsReadyDetail;
        "decompressError": DecompressErrorDetail;
    }
    interface HTMLWebReplayerElement extends Components.WebReplayer, HTMLStencilElement {
        addEventListener<K extends keyof HTMLWebReplayerElementEventMap>(type: K, listener: (this: HTMLWebReplayerElement, ev: WebReplayerCustomEvent<HTMLWebReplayerElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLWebReplayerElementEventMap>(type: K, listener: (this: HTMLWebReplayerElement, ev: WebReplayerCustomEvent<HTMLWebReplayerElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLWebReplayerElement: {
        prototype: HTMLWebReplayerElement;
        new (): HTMLWebReplayerElement;
    };
    interface HTMLWebStatsPanelElement extends Components.WebStatsPanel, HTMLStencilElement {
    }
    var HTMLWebStatsPanelElement: {
        prototype: HTMLWebStatsPanelElement;
        new (): HTMLWebStatsPanelElement;
    };
    interface HTMLWrTooltipElement extends Components.WrTooltip, HTMLStencilElement {
    }
    var HTMLWrTooltipElement: {
        prototype: HTMLWrTooltipElement;
        new (): HTMLWrTooltipElement;
    };
    interface HTMLElementTagNameMap {
        "heatmap-canvas": HTMLHeatmapCanvasElement;
        "replayer-controls": HTMLReplayerControlsElement;
        "stats-chart": HTMLStatsChartElement;
        "web-heatmap": HTMLWebHeatmapElement;
        "web-replayer": HTMLWebReplayerElement;
        "web-stats-panel": HTMLWebStatsPanelElement;
        "wr-tooltip": HTMLWrTooltipElement;
    }
}
declare namespace LocalJSX {
    type OneOf<K extends string, PropT, AttrT = PropT> = { [P in K]: PropT } & { [P in `attr:${K}` | `prop:${K}`]?: never } | { [P in `attr:${K}`]: AttrT } & { [P in K | `prop:${K}`]?: never } | { [P in `prop:${K}`]: PropT } & { [P in K | `attr:${K}`]?: never };

    interface HeatmapCanvas {
        /**
          * @default 'warm'
         */
        "colorScheme"?: HeatmapColorScheme;
        "data": HeatmapData;
        /**
          * @default 0.6
         */
        "opacity"?: number;
    }
    interface ReplayerControls {
        /**
          * @default 0
         */
        "currentTime"?: number;
        "onPlayPause"?: (event: ReplayerControlsCustomEvent<void>) => void;
        "onSeek"?: (event: ReplayerControlsCustomEvent<number>) => void;
        "onSpeedChange"?: (event: ReplayerControlsCustomEvent<number>) => void;
        /**
          * @default false
         */
        "playing"?: boolean;
        /**
          * @default 1
         */
        "speed"?: number;
        /**
          * @default 0
         */
        "totalTime"?: number;
    }
    interface StatsChart {
        "breakdown": OperationTally[];
    }
    interface WebHeatmap {
        /**
          * @default 'warm'
         */
        "colorScheme"?: HeatmapColorScheme;
        "events": RrwebEvent[];
        /**
          * @default 0.6
         */
        "opacity"?: number;
        /**
          * @default 'all'
         */
        "type"?: HeatmapType;
    }
    interface WebReplayer {
        /**
          * @default false
         */
        "autoPlay"?: boolean;
        "data": string;
        "height"?: number;
        "onDecompressError"?: (event: WebReplayerCustomEvent<DecompressErrorDetail>) => void;
        "onHeatmapReady"?: (event: WebReplayerCustomEvent<HeatmapReadyDetail>) => void;
        "onReplayFinish"?: (event: WebReplayerCustomEvent<void>) => void;
        "onReplayPause"?: (event: WebReplayerCustomEvent<void>) => void;
        "onReplayReady"?: (event: WebReplayerCustomEvent<ReplayReadyDetail>) => void;
        "onReplayStart"?: (event: WebReplayerCustomEvent<void>) => void;
        "onReplayTimeUpdate"?: (event: WebReplayerCustomEvent<ReplayTimeUpdateDetail>) => void;
        "onStatsReady"?: (event: WebReplayerCustomEvent<StatsReadyDetail>) => void;
        /**
          * @default true
         */
        "showControls"?: boolean;
        /**
          * @default false
         */
        "showHeatmap"?: boolean;
        /**
          * @default false
         */
        "showStats"?: boolean;
        /**
          * @default 1
         */
        "speed"?: number;
        /**
          * @default 0
         */
        "startTime"?: number;
        "width"?: number;
    }
    interface WebStatsPanel {
        "events": RrwebEvent[];
        /**
          * @default 'sidebar'
         */
        "layout"?: StatsPanelLayout;
        /**
          * @default ['clicks', 'scrolls', 'inputs', 'duration', 'path']
         */
        "metrics"?: StatsMetric[];
    }
    interface WrTooltip {
        /**
          * @default 'top'
         */
        "position"?: 'top' | 'bottom' | 'left' | 'right';
        "text": string;
    }

    interface HeatmapCanvasAttributes {
        "opacity": number;
        "colorScheme": HeatmapColorScheme;
    }
    interface ReplayerControlsAttributes {
        "playing": boolean;
        "currentTime": number;
        "totalTime": number;
        "speed": number;
    }
    interface WebHeatmapAttributes {
        "type": HeatmapType;
        "opacity": number;
        "colorScheme": HeatmapColorScheme;
    }
    interface WebReplayerAttributes {
        "data": string;
        "width": number;
        "height": number;
        "autoPlay": boolean;
        "speed": number;
        "showControls": boolean;
        "showHeatmap": boolean;
        "showStats": boolean;
        "startTime": number;
    }
    interface WebStatsPanelAttributes {
        "layout": StatsPanelLayout;
    }
    interface WrTooltipAttributes {
        "text": string;
        "position": 'top' | 'bottom' | 'left' | 'right';
    }

    interface IntrinsicElements {
        "heatmap-canvas": Omit<HeatmapCanvas, keyof HeatmapCanvasAttributes> & { [K in keyof HeatmapCanvas & keyof HeatmapCanvasAttributes]?: HeatmapCanvas[K] } & { [K in keyof HeatmapCanvas & keyof HeatmapCanvasAttributes as `attr:${K}`]?: HeatmapCanvasAttributes[K] } & { [K in keyof HeatmapCanvas & keyof HeatmapCanvasAttributes as `prop:${K}`]?: HeatmapCanvas[K] };
        "replayer-controls": Omit<ReplayerControls, keyof ReplayerControlsAttributes> & { [K in keyof ReplayerControls & keyof ReplayerControlsAttributes]?: ReplayerControls[K] } & { [K in keyof ReplayerControls & keyof ReplayerControlsAttributes as `attr:${K}`]?: ReplayerControlsAttributes[K] } & { [K in keyof ReplayerControls & keyof ReplayerControlsAttributes as `prop:${K}`]?: ReplayerControls[K] };
        "stats-chart": StatsChart;
        "web-heatmap": Omit<WebHeatmap, keyof WebHeatmapAttributes> & { [K in keyof WebHeatmap & keyof WebHeatmapAttributes]?: WebHeatmap[K] } & { [K in keyof WebHeatmap & keyof WebHeatmapAttributes as `attr:${K}`]?: WebHeatmapAttributes[K] } & { [K in keyof WebHeatmap & keyof WebHeatmapAttributes as `prop:${K}`]?: WebHeatmap[K] };
        "web-replayer": Omit<WebReplayer, keyof WebReplayerAttributes> & { [K in keyof WebReplayer & keyof WebReplayerAttributes]?: WebReplayer[K] } & { [K in keyof WebReplayer & keyof WebReplayerAttributes as `attr:${K}`]?: WebReplayerAttributes[K] } & { [K in keyof WebReplayer & keyof WebReplayerAttributes as `prop:${K}`]?: WebReplayer[K] } & OneOf<"data", WebReplayer["data"], WebReplayerAttributes["data"]>;
        "web-stats-panel": Omit<WebStatsPanel, keyof WebStatsPanelAttributes> & { [K in keyof WebStatsPanel & keyof WebStatsPanelAttributes]?: WebStatsPanel[K] } & { [K in keyof WebStatsPanel & keyof WebStatsPanelAttributes as `attr:${K}`]?: WebStatsPanelAttributes[K] } & { [K in keyof WebStatsPanel & keyof WebStatsPanelAttributes as `prop:${K}`]?: WebStatsPanel[K] };
        "wr-tooltip": Omit<WrTooltip, keyof WrTooltipAttributes> & { [K in keyof WrTooltip & keyof WrTooltipAttributes]?: WrTooltip[K] } & { [K in keyof WrTooltip & keyof WrTooltipAttributes as `attr:${K}`]?: WrTooltipAttributes[K] } & { [K in keyof WrTooltip & keyof WrTooltipAttributes as `prop:${K}`]?: WrTooltip[K] } & OneOf<"text", WrTooltip["text"], WrTooltipAttributes["text"]>;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "heatmap-canvas": LocalJSX.IntrinsicElements["heatmap-canvas"] & JSXBase.HTMLAttributes<HTMLHeatmapCanvasElement>;
            "replayer-controls": LocalJSX.IntrinsicElements["replayer-controls"] & JSXBase.HTMLAttributes<HTMLReplayerControlsElement>;
            "stats-chart": LocalJSX.IntrinsicElements["stats-chart"] & JSXBase.HTMLAttributes<HTMLStatsChartElement>;
            "web-heatmap": LocalJSX.IntrinsicElements["web-heatmap"] & JSXBase.HTMLAttributes<HTMLWebHeatmapElement>;
            "web-replayer": LocalJSX.IntrinsicElements["web-replayer"] & JSXBase.HTMLAttributes<HTMLWebReplayerElement>;
            "web-stats-panel": LocalJSX.IntrinsicElements["web-stats-panel"] & JSXBase.HTMLAttributes<HTMLWebStatsPanelElement>;
            "wr-tooltip": LocalJSX.IntrinsicElements["wr-tooltip"] & JSXBase.HTMLAttributes<HTMLWrTooltipElement>;
        }
    }
}
